use UNIVER;


SELECT 
min(AUDITORIUM_CAPACITY)[минимальная вместимость аудитории],
max(AUDITORIUM_CAPACITY)[максимальная вместимость аудитории],
count(*)[количество аудиторий], 
sum(AUDITORIUM_CAPACITY)[общая вместимость аудиторий],
AUDITORIUM_TYPE.AUDITORIUM_TYPE
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
	ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
	
	GROUP BY AUDITORIUM_TYPE.AUDITORIUM_TYPE

