use UNIVER;

SELECT f.FACULTY,
	   g.PROFESSION,
	   d.SUBJECT,
	   round(avg(cast (NOTE as float(4))),2)[Средняя оценка на экзамене]
FROM FACULTY f 
	INNER JOIN GROUPS g ON f.FACULTY = g.FACULTY 
	INNER JOIN STUDENT s ON g.IDGROUP = s.IDGROUP
	INNER JOIN PROGRESS d ON s.IDSTUDENT = d.IDSTUDENT
GROUP BY f.FACULTY, g.PROFESSION, g.YEAR_FIRST, d.SUBJECT




SELECT f.FACULTY,
	   g.PROFESSION,
	   d.SUBJECT,
	   round(avg(cast (NOTE as float(4))),2)[Средняя оценка на экзамене]
FROM FACULTY f 
	INNER JOIN GROUPS g ON f.FACULTY = g.FACULTY 
	INNER JOIN STUDENT s ON g.IDGROUP = s.IDGROUP
	INNER JOIN PROGRESS d ON s.IDSTUDENT = d.IDSTUDENT
	WHERE d.SUBJECT in('СУБД','ОАиП')
GROUP BY f.FACULTY, g.PROFESSION, g.YEAR_FIRST, d.SUBJECT


